<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>todo</string>
	</array>
	<key>name</key>
	<string>TODO</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^[0-9]+.*$</string>
			<key>name</key>
			<string>todo.category.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\*\t.*$</string>
			<key>name</key>
			<string>todo.priority1.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\*\*\t.*$</string>
			<key>name</key>
			<string>todo.priority2.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\*\*\*\t.*$</string>
			<key>name</key>
			<string>todo.priority3.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:.*\*{3,}$</string>
			<key>name</key>
			<string>todo.priority3.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:.*\*{2}$</string>
			<key>name</key>
			<string>todo.priority2.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:.*\*{1}$</string>
			<key>name</key>
			<string>todo.priority1.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bDone\b</string>
			<key>name</key>
			<string>todo.status.done.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bTodo\b</string>
			<key>name</key>
			<string>todo.status.todo.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bIn [Pp]rogress\b</string>
			<key>name</key>
			<string>todo.status.inprogress.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bNEW\b</string>
			<key>name</key>
			<string>todo.type.new.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bFIX\b</string>
			<key>name</key>
			<string>todo.type.fix.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bUPD\b</string>
			<key>name</key>
			<string>todo.type.upd.todo</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.todo</string>
	<key>uuid</key>
	<string>dd0aaebf-8d1f-4e26-8ef7-dfe957e2878a</string>
</dict>
</plist>
